name: Build Windows EXE

on:
  push:
    branches: [ windows-build ]
  pull_request:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install requests Pillow youtube-search-python ttkbootstrap

    - name: Build EXE
      run: |
        pyinstaller --onefile --windowed --hidden-import=youtube_search main.py
        # Als je een icoon wilt, kan je hier toevoegen:
        # pyinstaller --onefile --icon=icon.ico main.py

    - name: Upload EXE als artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-build
        path: dist/main.exe
