name: Build Windows EXE and push to new branch

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    # 1. Checkout repo
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Setup Python
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    # 3. Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    # 4. Build EXE
    - name: Build EXE
      run: |
        pyinstaller --onefile main.py

    # 5. Setup Git
    - name: Setup Git
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@users.noreply.github.com"

    # 6. Commit EXE to new branch using PAT
    - name: Commit EXE to new branch
      env:
        PAT_TOKEN: ${{ secrets.PAT_TOKEN }}   
      run: |
        git checkout -b windows-build
        mkdir -p exe
        mv dist/main.exe exe/
        git add exe/main.exe
        git commit -m "Add Windows EXE build"
        git push --set-upstream https://jonasvanleeuwen19:${PAT_TOKEN}@github.com/jonasvanleeuwen19/youtube-player.git windows-build

    # 7. Upload artifact 
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-exe
        path: exe/main.exe
